import React, { useState, useRef, useEffect, useContext } from 'react';
import { ResultsContext } from "../../context/result"; 
import { X, MapPin, Plus } from 'lucide-react';

const TagInput = () => {
  const { setLocations } = useContext(ResultsContext);
  const [tags, setTags] = useState([]);
  const [inputValue, setInputValue] = useState('');
  const [showSuggestions, setShowSuggestions] = useState(false);
  const inputRef = useRef(null);
  const suggestionRef = useRef(null);

  const suggestions = [
    "Paris",
    "Bordeaux",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Montpellier",
    "Strasbourg",
    "Lille",
    "Rennes",
    "Toulon",
    "Reims",
    "Saint-Étienne",
    "Le Havre",
    "Dijon",
    "Grenoble",
    "Angers",
    "Villeurbanne",
    "Nîmes",
    "Aix-en-Provence",
    "Clermont-Ferrand",
    "Le Mans",
    "Brest",
    "Tours",
    "Amiens",
    "Annecy",
    "Limoges",
    "Metz",
    "Boulogne-Billancourt",
    "Perpignan",
    "Besançon",
    "Orléans",
    "Rouen",
    "Saint-Denis",
    "Montreuil",
    "Caen",
    "Argenteuil",
    "Mulhouse",
    "Nancy",
    "Tourcoing",
    "Roubaix",
    "Nanterre",
    "Vitry-sur-Seine",
    "Créteil",
    "Poitiers",
    "Aubervilliers",
    "Colombes",
    "Dunkerque",
    "Aulnay-sous-Bois",
    "Versailles",
    "Courbevoic",
    "La Rochelle",
    "Rueil-Malmaison",
    "Champigny-sur-Marne",
    "Pau",
    "Mérignac",
    "Saint-Maur-des-Fossés",
    "Antibes",
    "Ajaccio",
    "Cannes",
    "Saint-Nazaire",
    "Drancy",
    "Noisy-le-Grand",
    "Issy-les-Moulineaux",
    "Cergy",
    "Levallois-Perret",
    "Calais",
    "Pessac",
    "Vénissieux",
    "Clichy",
    "Valence",
    "Ivry-sur-Seine",
    "Antony",
    "Troyes",
    "La Seyne-sur-Mer",
    "Pantin",
    "Chambéry",
    "Neuilly-sur-Seine",
    "Sarcelles",
    "Le Blanc-Mesnil",
    "Maisons-Alfort",
    "Lorient",
    "Villejuif",
    "Bellevue",
    "Beauvais",
    "Meaux",
    "Bobigny",
    "Clamart",
    "Vannes",
    "Chelles",
    "Évry",
    "Épinay-sur-Seine",
    "Saint-Ouen",
    "Saint-Quentin",
    "Bondy",
    "Bayonne",
    "Corbeil-Essonnes",
    "Cagnes-sur-Mer",
    "Vaulx-en-Velin",
    "Sevran",
    "Fontenay-sous-Bois",
    "Sartrouville",
    "Massy",
    "Laval",
    "Saint-Herblain",
    "Gennevilliers",
    "Suresnes",
    "Saint-Priest",
    "Vincennes",
    "Bastia",
    "Montrouge",
    "Évreux",
    "La Courneuve",
    "Charleville-Mézières",
    "Meudon",
    "Choisy-le-Roi",
    "Noisy-le-Sec",
    "Livry-Gargan",
    "Rosny-sous-Bois",
    "Talence",
    "Belfort",
    "Alfortville",
    "Chalon-sur-Saône",
    "Sète",
    "Mantes-la-Jolie",
    "Saint-Brieuc",
    "Tarbes",
    "Alès",
    "Châlons-en-Champagne",
    "Bagneux",
    "Puteaux",
    "Caluire-et-Cuire",
    "Bron",
    "Rezé",
    "Valenciennes",
    "Châteauroux",
    "Garges-lès-Gonesse",
    "Arras",
    "Melun",
    "Le Cannet",
    "Bourg-en-Bresse",
    "Anglet",
    "Angoulême",
    "Boulogne-sur-Mer",
    "Wattrelos",
    "Villenave-d’Ornon",
    "Stains",
    "Gagny",
    "Colomiers",
    "Poissy",
    "Douai",
    "Bagnolet",
    "Marcq-en-Baroeul",
    "Villepinte",
    "Saint-Martin-d’Hères",
    "Chartres",
    "Annemasse",
    "Neuilly-sur-Marne",
    "Franconville",
    "Savigny-sur-Orge",
    "Thonon-les-Bains",
    "Échirolles",
    "Châtillon",
    "Athis-Mons",
    "Creil",
    "Conflans-Sainte-Honorine",
    "Villefranche-sur-Saône",
    "Meyzieu",
    "Sainte-Geneviève-des-Bois",
    "Villeneuve-Saint-Georges",
    "Châtenay-Malabry",
    "Palaiseau",
    "Roanne",
    "Le Perreux-Sur-Marne",
    "Schiltigheim",
    "Les Mureaux",
    "Trappes",
    "Nogent-sur-Marne",
    "Houilles",
    "Montluçon",
    "Romainville",
    "Nevers",
    "Lens",
    "Agen",
    "Pierrefitte-sur-Seine",
    "Bezons",
    "Aix-les-Bains",
    "Montigny-le-Bretonneux",
    "Cambrai",
    "L’Haÿ-les-Roses",
    "Plaisir",
    "Pontoise",
    "Rillieux-la-Pape",
    "Thiais",
    "Vigneux-sur-Seine",
    "Viry-Châtillon",
    "Saint-Laurent-du-Var",
    "Bègles",
    "Goussainville",
    "Villiers-sur-Marne",
    "Cachan",
    "Savigny-le-Temple",
    "Menton",
    "Villemomble",
    "Malakoff",
    "Liévin",
    "La Garenne-Colombes",
    "Ris-Orangis",
    "Bois-Colombes",
    "Clichy-sous-Bois",
    "Décines-Charpieu",
    "Saint-Cloud",
    "Chatou",
    "Vandœuvre-lès-Nancy",
    "Périgueux",
    "Charenton-le-Pont",
    "Tournefeuille",
    "Guyancourt",
    "Le Plessis-Robinson",
    "Draveil",
    "Maubeuge",
    "Ermont",
    "Sotteville-lès-Rouen",
    "Villiers-le-Bel",
    "Fresnes",
    "Soissons",
    "Yerres",
    "Saint-Étienne-du-Rouvray",
    "Dieppe",
    "Saint-Sébastien-sur-Loire",
    "Vallauris",
    "Vanves",
    "Lomme",
    "Limeil-Brévannes",
    "Montfermeil",
    "Le Chesnay",
    "Sucy-en-Brie",
    "Grigny",
    "Lambersart",
    "Brétigny-sur-Orge",
    "Taverny",
    "Oullins",
    "Villeparisis",
    "Cenon",
    "Sannois",
    "Cormeilles-en-Parisis",
    "Bussy-Saint-Georges",
    "Blagnac",
    "Élancourt",
    "Le Grand-Quevilly",
    "La Garde",
    "Gradignan",
    "Vichy",
    "Biarritz",
    "Champs-Sur-Marne",
    "Armentières",
    "Montbéliard",
    "Alençon",
    "Brunoy",
    "Eaubonne",
    "Villeneuve-la-Garenne",
    "Cherbourg",
    "Saint-Ouen-l’Aumône",
    "Béthune",
    "Castelnau-le-Lez",
    "Fontenay-aux-Roses",
    "Orly",
    "Le Kremlin-Bicêtre",
    "Eysines",
    "Le Bouscat",
    "Rodez",
    "Les Pavillons-sous-Bois",
    "La Valette-du-Var",
    "Montgeron",
    "Les Lilas",
    "Lormont",
    "Maisons-Laffitte",
    "Roissy-en-Brie",
    "Loos",
    "Fontaine",
    "Dammarie-lè-Lys",
    "Vélizy-Villacoublay",
    "Tassin-la-Demi-Lune",
    "Sèvres",
    "Montigny-lès-Cormeilles",
    "Deuil-la-Barre",
    "La Madeleine",
    "Torcy",
    "Montereau-faut-Yonne",
    "Combs-la-Ville",
    "Hérouville-Saint-Clair",
    "Montmorency",
    "Sainte-Foy-lès-Lyon",
    "Montigny-lès-Metz",
    "Le Petit-Quevilly",
    "Saint-Jean-de-Braye",
    "Arcueil",
    "Mons-en-Baroeul",
    "Fleury-les-Aubrais",
    "Saint-Michel-sur-Orge",
    "Neuilly-Plaisance",
    "Nogent-sur-Oise",
    "Mantes-la-Ville",
    "Achères",
    "Saint-Mandé",
    "Villeneuve-le-Roi",
    "Saint-Cyr-l’École",
    "Saint-Genis-Laval",
    "Saint-Gratien",
    "Wasquehal",
    "Halluin",
    "Bourg-la-Reine",
    "Morsang-sur-Orge",
    "Croix",
    "Coudekerque-Branche",
    "Fougères",
    "Denain",
    "Longjumeau",
    "Sceaux",
    "Saint-Pol-sur-Mer",
    "La Celle-Saint-Cloud",
    "Joinville-le-Pont",
    "Cugnaux",
    "Chevilly-Larue",
    "Lingolsheim",
    "Le Plessis-Trévise",
    "Le Mée-sur-Seine",
    "Mont-Saint-Aignan",
    "Chaville",
    "Chilly-Mazarin",
    "Lisieux",
    "Ronchin",
    "Saint-Fons",
    "Moulins",
    "Villefontaine",
    "Gentilly",
    "Bonneuil-sur-Marne",
    "Hem",
    "Maurepas",
    "Meylan",
    "Éragny",
    "Hellemmes-Lille",
    "Juvisy-sur-Orge",
    "Chennevières-sur-Marne",
    "Écully",
    "Cran-Gévrier",
    "Carrières-sous-Poissy",
    "Rosendaël",
    "Fâches-Thumesnil",
    "Soisy-sous-Montmorency",
    "Bischheim",
    "Garches",
    "Hendaye",
    "Floirac",
    "Limay",
    "Boissy-Saint-Léger",
    "Le Pontet",
    "Chamalières",
    "Bry-sur-Marne",
    "Les Clayes-sous-Bois",
    "L’Isle-d’Abeau",
    "Jouy-le-Moutier",
    "Cluses",
    "Firminy",
    "Lons-le-Saunier",
    "Saint-Égrève",
    "Viroflay",
    "Octeville",
    "Le Pré-Saint-Gervais",
    "Saint-Jean-de-la-Ruelle",
    "Marly-le-Roi",
    "Domont",
    "Vauréal",
    "Orsay",
    "Saint-Leu-la-Forêt",
    "Verneuil-sur-Seine",
    "Petite-Synthe",
    "Saint-Julien-en-Genevois",
    "Le Pecq",
    "Le Vésinet",
    "Lucé",
    "Wattignies",
    "Noisiel",
    "Bois-d’Arcy",
    "Rive-de-Gier",
    "Saint-Brice-sous-Forêt",
    "Francheville",
    "Longwy",
    "Vesoul",
    "Montargis",
    "Carrières-sur-Seine",
    "Ramonville-Saint-Agne",
    "Castanet-Tolosan",
    "Le Raincy",
    "Le Bourget",
    "Illzach",
    "Montmagny",
    "Villers-lès-Nancy",
    "Haubourdin",
    "Dinan",
    "Lognes",
    "Saint-Maurice",
    "Verrières-le-Buisson",
    "Arnouville-lès-Gonesse",
    "Saint-Genis-Pouilly",
    "Les Sables-d’Olonne",
    "Montesson",
    "Valenton",
    "Chenôve",
    "Bois-Guillaume",
    "Auray",
    "Persan",
    "Fleury-Mérogis",
    "Audincourt",
    "Montévrain",
    "Billère",
    "Lys-lès-Lannoy",
    "Avon",
    "Vaires-sur-Marne",
    "Courcouronnes",
    "Fontenay-le-Fleury",
    "Anzin",
    "Ostwald",
    "Outreau",
    "Andrésy",
    "Morangis",
    "Kingersheim",
    "Mouvaux",
    "Saint-André",
    "Saint-André-les-Vergers",
    "Bayeux",
    "Beausoleil",
    "L’Union",
    "Bully-les-Mines",
    "Riedisheim",
    "Marly",
    "Craponne",
    "Talant",
    "Épinay-sous-Sénart",
    "Le Relecq-Kerhuon",
    "Villecresnes",
    "Hœnheim",
    "Vitry-le-François",
    "Enghien-les-Bains",
    "Méricourt",
    "Yvetot",
    "Dugny",
    "Bruay-sur-l’Escaut",
    "Saint-Germain-lès-Arpajon",
    "Arpajon",
    "Arcachon",
    "Saint-Jean",
    "Marquette-lès-Lille",
    "Cesson",
    "Stiring-Wendel",
    "Maromme",
    "Ferney-Voltaire",
    "Bondoufle",
    "Le Pont-de-Claix",
    "Épinay-sur-Orge",
    "Déville-lès-Rouen",
    "Chanteloup-les-Vignes",
    "Voisins-le-Bretonneux",
    "Ville-d’Avray",
    "Beaumont",
    "Flers-lez-Lille",
    "Tinqueux",
    "Ormesson-sur-Marne",
    "Pierre-Bénite",
    "Clermont",
    "Thorigny-sur-Marne",
    "Croissy-sur-Seine",
    "Villeneuve-Tolosane",
    "Avranches",
    "Pfastatt",
    "Igny",
    "Oignies",
    "Gaillard",
    "Neuville-en-Ferrain",
    "Caudebec-lès-Elbeuf",
    "Saint-Max",
    "Villerupt",
    "Auchel",
    "Vernouillet",
    "Aniche",
    "Eybens",
    "Fosses",
    "Maxéville",
    "Montigny-en-Gohelle",
    "Grigny",
    "Darnétal",
    "Serris",
    "Sallaumines",
    "Neuville-lès-Dieppe",
    "Beaumont-sur-Oise",
    "Leers",
    "Ézanville",
    "Pérols",
    "Crosne",
    "Quincy-sous-Sénart",
    "Jarville-la-Malgrange",
    "Aucamville",
    "Hagondange",
    "Le Crès",
    "Bures-sur-Yvette",
    "Évian-les-Bains",
    "Ville-la-Grand",
    "Beauchamp",
    "Magny-le-Hongre",
    "Bougival",
    "Tomblaine",
    "Le Portel",
    "Fontaine-lès-Dijon",
    "Boucau",
    "Essey-lès-Nancy",
    "Wingles",
    "Montlhéry",
    "L’Île-Saint-Denis",
    "Vaucresson",
    "La Salvetat-Saint-Gilles",
    "Pérenchies",
    "Saint-Aubin-lès-Elbeuf",
    "Groslay",
    "Le Plessis-Bouchard",
    "Meythet",
    "Terrenoire",
    "Harfleur",
    "Carbon-Blanc",
    "Courcelles-les-Lens",
    "Bihorel",
    "La Tour-du-Pin",
    "Souffelweyersheim",
    "Billy-Montigny",
    "La Ville-du-Bois",
    "Coulaines",
    "Boussy-Saint-Antoine",
    "Le Mesnil-Esnard",
    "Talange",
    "Cappelle-la-Grande",
    "Beauzelle",
    "Vaujours",
    "Saint-Germain-lès-Corbeil",
    "Terville",
    "Waziers",
    "Huningue",
    "Villemoisson-sur-Orge",
    "Sainte-Adresse",
    "Guingamp",
    "Fontaines-sur-Saône",
    "Liancourt",
    "Courtry",
    "Gournay-sur-Marne",
    "Sathonay-Camp",
    "Jacou",
    "Beuvrages",
    "Égly",
    "Carnoux-en-Provence",
    "Grenay",
    "Luisant",
    "Noyelles-sous-Lens",
    "La Bassée",
    "Neuves-Maisons",
    "La Mulatière",
    "Bouffémont",
    "La Penne-sur-Huveaune",
    "Jœuf",
    "Cognin",
    "La Montagne",
    "Bonsecours",
    "Saint-Alban",
    "L’Arbresle",
    "Esbly",
    "Le Mesnil-le-Roi",
    "Fouquières-lès-Lens",
    "La Verrière",
    "Ambilly",
    "Saint-Priest-en-Jarez",
    "Magnanville",
    "Pont-de-Chéruy",
    "Menucourt",
    "Ablon-sur-Seine",
    "Champagne-au-Mont-d’Or",
    "Palavas-les-Flots",
    "Saintry-sur-Seine",
    "Saint-André-de-la-Roche",
    "Longueau",
    "Le Port-Marly",
    "Oberhausbergen",
    "Heillecourt",
    "Crégy-lès-Meaux",
    "Loison-sous-Lens",
    "Montaigu",
    "Bassens",
    "Grand-Fort-Philippe",
    "Mandres-les-Roses",
    "La Frette-sur-Seine",
    "Le Ban-Saint-Martin",
    "Saint-Nicolas",
    "Villiers-sur-Orge",
    "Cap-d’Ail",
    "Nilvange",
    "Leuville-sur-Orge",
    "Jacob-Bellecombette",
    "Valras-Plage",
    "Avesnes-sur-Helpe",
    "Ascq",
    "Longeville-lès-Metz",
    "Neuville-Saint-Rémy",
    "Toufflers",
    "Mareil-Marly",
    "Lourches",
    "Beaulieu-sur-Mer",
    "Sochaux",
    "Bergues",
    "Barby",
    "Fort-Mardyck",
    "Neauphle-le-Château",
    "Saint-Mammès",
    "Les Noës-près-Troyes",
    "Pont-à-Vendin",
    "Rouelles",
    "Paimbœuf",
    "Courchelettes",
    "Éleu-dit-Leauwette",
    "Port-Louis",
    "Sainte-Foy-la-Grande"
  ].sort();
  
  const filteredSuggestions = suggestions.filter(
    city => city.toLowerCase().includes(inputValue.toLowerCase()) &&
    !tags.includes(city)
  );

  useEffect(() => {
    setLocations(tags);
  }, [tags, setLocations]);

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (suggestionRef.current && !suggestionRef.current.contains(event.target) &&
          !inputRef.current.contains(event.target)) {
        setShowSuggestions(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && inputValue.trim() !== '') {
      e.preventDefault();
      const matchedCity = suggestions.find(
        city => city.toLowerCase() === inputValue.toLowerCase()
      );
      if (matchedCity && !tags.includes(matchedCity)) {
        setTags([...tags, matchedCity]);
        setInputValue('');
        setShowSuggestions(false);
      }
    }
  };

  const addTag = (suggestion) => {
    if (!tags.includes(suggestion)) {
      setTags([...tags, suggestion]);
      setInputValue('');
      setShowSuggestions(false);
    }
  };

  const removeTag = (indexToRemove) => {
    setTags(tags.filter((_, index) => index !== indexToRemove));
  };

  return (
    <div className="w-full">
      <div className="group relative w-full">
        <MapPin className="absolute left-3 top-4 text-gray-500 group-focus-within:text-blue-400 transition-colors z-10" />
        <div className="min-h-[100px] w-full p-2 pl-12 bg-gray-800/50 border border-gray-700 
                    rounded-lg flex flex-wrap gap-2 items-start backdrop-blur-sm
                    focus-within:ring-2 focus-within:ring-blue-500 focus-within:border-transparent
                    transition-all duration-200">
          {tags.map((tag, index) => (
            <div
              key={index}
              className="flex items-center gap-1 bg-blue-600/20 border border-blue-500/30 
                       px-3 py-1 rounded-full backdrop-blur-sm group hover:bg-blue-600/30 
                       transition-all duration-200"
            >
              <span className="text-sm text-gray-100">{tag}</span>
              <button
                onClick={() => removeTag(index)}
                className="text-gray-400 hover:text-red-400 rounded-full p-0.5
                         opacity-70 group-hover:opacity-100 transition-all duration-200"
              >
                <X size={14} />
              </button>
            </div>
          ))}
          <input
            ref={inputRef}
            type="text"
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyDown={handleKeyDown}
            onFocus={() => setShowSuggestions(true)}
            placeholder="Entrez le nom d'une ville"
            className="flex-grow min-w-[200px] bg-transparent outline-none text-gray-100 
                     placeholder:text-gray-500 py-1"
          />
        </div>
        
        {showSuggestions && filteredSuggestions.length > 0 && (
          <div 
            ref={suggestionRef}
            className="absolute left-0 right-0 mt-2 bg-gray-800/95 border border-gray-700 
                     shadow-lg rounded-lg overflow-hidden max-h-60 overflow-y-auto
                     backdrop-blur-sm z-50"
          >
            {filteredSuggestions.map((suggestion) => (
              <button
                key={suggestion}
                onClick={() => addTag(suggestion)}
                className="w-full text-left px-4 py-2 text-gray-100 hover:bg-blue-600/20 
                         focus:bg-blue-600/20 focus:outline-none transition-colors duration-200
                         flex items-center justify-between group"
              >
                <span>{suggestion}</span>
                <Plus size={14} className="opacity-0 group-hover:opacity-100 text-blue-400 transition-opacity duration-200" />
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default TagInput;